Fix Mend SCA and SAST scans

diff --git a/.github/workflows/mend-cli-scan.yaml b/.github/workflows/mend-cli-scan.yaml
--- a/.github/workflows/mend-cli-scan.yaml
+++ b/.github/workflows/mend-cli-scan.yaml
@@ -62,6 +62,7 @@ jobs:
           MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
           MEND_URL: ${{ vars.MEND_SERVER_URL }}
         shell: bash
+        timeout-minutes: 20
         run: |
           mend dep --no-color -s ${{ vars.MEND_PRODUCT_NAME }}//${{ vars.MEND_PROJECT_NAME }} -u > mend-sca-scan-result.txt
 
@@ -90,9 +91,16 @@ jobs:
             echo "✅ No critical/high SCA vulnerabilities."
           fi
 
+      - name: Debug the SCA scan result file
+        if: always()
+        run: |
+          echo "SCA result file:"
+          ls -lah mend-sca-scan-result.txt || echo "mend-sca-scan-result.txt file not found"
+          cat mend-sca-scan-result.txt || echo "mend-sca-scan-result.txt file is empty"
+
       # Publish the Mend SCA scan result
-      - name: Mend SCA Scan Result
-        uses: LouisBrunner/checks-action@v1.6.1
+      - name: Publish Mend SCA Scan Result
+        uses: LouisBrunner/checks-action@v2.0.0
         if: always()
         with:
           name: "Mend SCA Scan Result"
@@ -112,8 +120,10 @@ jobs:
           MEND_URL: ${{ vars.MEND_SERVER_URL }}
           MEND_SAST_PATH_EXCLUSIONS: ${{ vars.MEND_SAST_PATH_EXCLUSIONS }}
         shell: bash
+        timeout-minutes: 20
+        if: always()
         run: |
-          mend code --report --filename ${{ vars.MEND_SAST_REPORT_NAME }} --formats json,pdf --non-interactive --scope ${{ vars.MEND_PRODUCT_NAME }}//${{ vars.MEND_PROJECT_NAME }} > mend-sast-scan-result.txt
+          mend code --report --filename ${{ vars.MEND_SAST_REPORT_NAME }} --formats json --non-interactive --scope ${{ vars.MEND_PRODUCT_NAME }}//${{ vars.MEND_PROJECT_NAME }} > mend-sast-scan-result.txt
 
           export MEND_SAST_TOTAL_VULNERABILITIES_COUNT=$(jq '.[0].stats.totalVulnerabilities' ${{ vars.MEND_SAST_REPORT_NAME }}.json)
           export MEND_SAST_CRITICAL_COUNT=$(jq '.[0].stats.critical' ${{ vars.MEND_SAST_REPORT_NAME }}.json)
@@ -132,6 +142,7 @@ jobs:
       # Check for failures in SAST scan and set the outcome of the workflow
       - name: Fail if Critical or High SAST vulnerabilities are found
         shell: bash
+        if: always()
         run: |
           if [ "$MEND_SAST_CRITICAL_COUNT" -gt 0 ] || [ "$MEND_SAST_HIGH_COUNT" -gt 0 ]; then
             echo "❌ SAST scan detected critical/high vulnerabilities."
@@ -140,9 +151,16 @@ jobs:
             echo "✅ No critical/high SAST vulnerabilities."
           fi
 
+      - name: Debug the SAST scan result file
+        if: always()
+        run: |
+          echo "SAST result file:"
+          ls -lah mend-sast-scan-result.txt || echo "mend-sast-scan-result.txt file not found"
+          cat mend-sast-scan-result.txt || echo "File mend-sast-scan-result.txt file is empty"
+
       # Publish the Mend SAST scan result (raw output)
-      - name: Mend SAST Scan Result
-        uses: LouisBrunner/checks-action@v1.6.1
+      - name: Publish Mend SAST Scan Result
+        uses: LouisBrunner/checks-action@v2.0.0
         if: always()
         with:
           name: "Mend SAST Scan Result"
@@ -151,19 +169,21 @@ jobs:
           output_text_description_file: mend-sast-scan-result.txt
           output: |
             {"title":"Mend SAST Scan Result", "summary":"${{ job.status }}"}
-
-      # Publish the Mend SAST scan result (PDF report)
-      - name: Publish${{ vars.MEND_SAST_REPORT_NAME }}.pdf
+      
+      # Publish the Mend SCA and SAST scan results
+      - name: Upload scan reports
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: ${{ vars.MEND_SAST_REPORT_NAME }}.pdf
-          path: ${{ vars.MEND_SAST_REPORT_NAME }}.pdf
+          name: mend-scan-reports
+          path: |
+            mend-sca-scan-result.txt
+            mend-sast-scan-result.txt
 
-      
       # Send slack notification with result status
       - name: Send slack notification
         uses: 8398a7/action-slack@v3
+        if: always()
         with:
           status: custom
           fields: all
@@ -190,4 +210,3 @@ jobs:
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
-        if: always()
